name:  04-using-actions

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
                - name: checkout code
                  uses: actions/checkout@v4
                - name: Setup node
                  uses: actions/Setup-node@v3
                  with:
                    node-version: '20.x'
                - name: install dependencies
                  run: npm ci    
                  working-directory: /home/runner/work/GHA/GHA/GHA/04-using-actions/react-app
 
        # checkout the code from repo
        # install dependencies of react application
        # executed automated test

  