
name: 07 - Using Expressions
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "enabling debig mode"
        required: false
        default: false
        type: boolean
    

jobs:
  echo:
    runs-on: ubuntu-latest
    