name: 09 - Using Functions

on: 
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
            - name: Print ENV vaiables
              run: |
               echo "welcome" 

