name: 09 - Using Functions

on: 
    pull_request: 
    workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
        - name: Failing Step
          run : exit 1
        #- name: I will be skipped
        #- name: I will execute
         