name: test - 01

on: 
    - workflow_dispatch

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: test run
              run: echo "welcome"
              
        
    

